### ISSUE TITLE
[Feature] Support same color accros palettes but with different material settings

### ISSUE THREAD

**Issue by MaximilianGaedig** [Zarbuz/VoxMerger#10]
Some Vox files have their emissions removed after the merge, example file:
[file2.vox.zip](https://github.com/Zarbuz/VoxMerger/files/8402780/file2.vox.zip)

**Comment by Zarbuz** [comment]
Hi, I test your example file and I saw why the emissive property isn't saved. You have in your palette, two slots with the same colors and the second one (which is not really the 2nd by the way but rather the first in the order of the palette) is the default material.
![image](https://user-images.githubusercontent.com/4965714/161509267-0c417414-4efd-4950-a0c6-57bbb951159a.png)
VoxMerger doesn't keep duplicates by color. If you change the color of the slot, you will see that materials informations are correctly kept. 
![image](https://user-images.githubusercontent.com/4965714/161509517-ff0a9bb6-335b-4524-be99-5dce6ec6b559.png)

**Comment by Zarbuz** [comment]
Made for the version v0.09
